### ISSUE TITLE
[BUG] Performance issues

### ISSUE THREAD

**Issue by amcvfx** [p4535992/token-factions#3] opened 2022-01-07 11:31 UTC
**Module Version:** v0.2.15

**Describe the bug**
With Token Factions active there is a very noticeable lag on larger scenes when switching tools (tokens, walls, tiles etc...) with a significant FPS loss (from 144fps down to 50-60fps). 
The FPS loss seems permanent in a scene after a tool has been switched i.e. the FPS is locked under 60fps.

**To Reproduce**
With only Token Factions and Libwrapper active the issues are apparent.

**Screenshots**
Screenshot of FPS before switching tools on a large scene (only Token Factions and Libwrapper active).
![image](https://user-images.githubusercontent.com/35099081/148537630-dafcdfad-b0c8-4d60-ac3b-147f3c336f93.png)

FPS when using Walls tool
![image](https://user-images.githubusercontent.com/35099081/148537741-48cf5a98-314a-43de-afac-b0de4c1be4f7.png)

FPS after switching back to Token select tool
![image](https://user-images.githubusercontent.com/35099081/148537824-5e19fa49-baa8-4110-898e-6cfe3aba1eae.png)

**Browser:**
Chrome

**Foundry Version:** 
v9

**Game System:** 
DND 5e 1.5.6

I love this module btw!

**Comment by p4535992** [comment] 2022-01-20 21:12
Sorry about the long abscence , i'm not forgot about this.

**Comment by dev7355608** [comment] 2022-03-06 15:14
This is probably caused by #8.

**Comment by p4535992** [comment] 2022-03-12 23:11
should be solved from [Change game.data.version to game.version](https://github.com/p4535992/token-factions/pull/9) ty for the contribution

**Comment by p4535992** [comment] 2022-03-19 17:32
Should be fixed on 0.2.17

**Closed** 2022-04-11 09:51 UTC
Labels: bug, probably fixed
